name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

  # Run build for any PRs.
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: kazuhikotsuji/myimage
          tags: js
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
